# https://stackoverflow.com/questions/76150514/running-docker-inside-a-container
#
# kubectl create -f docker-pod.yml
# kubectl exec -it docker -- sh -c "docker version"
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:latest
        #24.0.0-rc.1-dind
        securityContext:
          privileged: true
        command: ["sh", "-c" ]
        args:
        - |
          #!/usr/bin/env bash
          #
          set -x
          export DATETIME=$(date +%Y%m%d_%H%M%S)
          #apt install -y curl apt-utils
          #docker run hello-world
