apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c" ]
        args:
        - |
          #!/usr/bin/env bash
          #
          export DATETIME=$(date +%Y%m%d_%H%M%S)
          apt update
          apt install -y curl apt-utils
          perl -pi -e "s/sleep 20/echo/g;" get-docker.sh
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker run hello-world
        
